### PR TITLE
add colorpicker stylesheet

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@stulees these are all the styles I had. some might be already useless because of the recent changes.

### CODE REVIEW

**Comment by stulees** [comment]
@ghislaineguerin I'm not sure all of these should be within `colorpicker.scss` as a lot don't really pertain to the color picker per se. It might be hard to find the likes of `.image-placeholder`, `.background-group`, `.color-wheel`, etc when a potential future change needs doing. Any chance you could separate some of this out to be in other `.scss` file(s) within `ui-components/`?

**Comment by stulees** [comment]
@ghislaineguerin Made the changes, please review, thanks

**Comment by stulees** [comment]
@donnapep Could you review actually, thanks

**Comment by donnapep** [comment]
@stulees I defer to you on which file these styles go into.

But, is it possible to use a background url that does not specify a protocol (e.g. `url('//s3.amazonaws.com/Rise-Images/UI/transp_bg.png')`)? `http` would work OK now if all of our Widgets use `http`, but I have a feeling we may want to switch at some point since `https` is more widely accepted. And if this was still using `http`, it wouldn't work in those Widgets.

Thx.

**Comment by stulees** [comment]
@donnapep Good call, have made the change.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
