### PR TITLE
added media break for font-settings

### PR DESCRIPTION
**Pull request by mmeiers**
@stulees @ghislaineguerin 
Here is a PR for the media query I added to the font-setting.scss.

I noticed that the npm-debug.log and package.json updated with new versions of the modules. Should I take those out of the commit?

### CODE REVIEW

**Comment by stulees** [comment]
@mmeiers I think a class name more directly related to Font Setting would be better like `.font-setting`. Using `.media-break` seems too broad, but I'll defer to @ghislaineguerin and also defer to her on the other files getting updated as I'm not sure why they would be changing. Thanks

**Comment by ghislaineguerin** [comment]
@mmeiers I agree with @stulees on this one. I think we also want to stick with our standard breakpoints
320 480 768 992 and 1200 px, 320 and 480 only if really needed, otherwise everything under 768px should be able to go lower and still look ok. Let's go through this tomorrow morning.

**Comment by mmeiers** [comment]
@ghislaineguerin @stulees 
I have changed the class names as well as changed the media query to be 768.

**Comment by ghislaineguerin** [comment]
@mmeiers yes, those need to be omitted, also the output css file with the inline comments.
As for the media breaks, I've been looking into the structure of the font-settings and there are many things that need to be cleaned up, a lot of floating classes that are not needed but we can do this later.
Based on your video I'd say go ahead and add the extra breakpoint. Once we solve the other style issues we can find a better way to do this.

**Pull request closed without merging**
