### PR TITLE
Intercom layout changes

### PR DESCRIPTION
**Pull request by RV-Adrian**
@ezequielc @alex-deaconu @ghislaineguerin 
Pull request for https://trello.com/c/BZeUaQNO/1431-ux-intercom-bubble-widget-ui-2

### CODE REVIEW

**Comment by ezequielc** [comment]
@RV-Adrian Looks good, but I will defer to @ghislaineguerin . Thanks!

**Comment by ezequielc** [comment]
@RV-Adrian I just saw this PR. Are we going to merge it? Thanks

**Comment by RV-Adrian** [comment]
@ezequielc 
Need to confirm with @ghislaineguerin , will aim for this today!

**Comment by ghislaineguerin** [comment]
👍

**Comment by RV-Adrian** [comment]
@ghislaineguerin Thx!
@ezequielc I'll resolve conflicts and then merge.

**Pull request merged**
