### PR TITLE
Feature/display settings

### PR DESCRIPTION
**Pull request by ghislaineguerin**

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@ezequielc @RV-Adrian @alex-deaconu @settinghead
I have staged the common styles changes needed for display settings. I think that as part of our process we should aim to merge all branches after dev handoff even if dev hasn't started so that we are sure at the moment that implementation won't break anything.
The rule should be that all common style branches, at the moment of dev handoff shouldn't break anything on production, ever. If there is a case where a future cleanup will be needed it should be added to a card for technical debt reduction. Let me know what you think. thanks 
STAGE: https://apps-stage-3.risevision.com/

**Comment by RV-Adrian** [comment]
@ghislaineguerin Sounds like a good idea to me, one less thing to keep track of.

**Comment by ezequielc** [comment]
@ghislaineguerin Sounds good to me. As you said, this should be the goal, and when it is not achievable we treat it as an exception. Thanks!

**Comment by alex-deaconu** [comment]
@ghislaineguerin looks good, no issues from what I can tell. Wondering if you could double check this version with the Store as well. Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu will do.

**Comment by ghislaineguerin** [comment]
@RV-Adrian @ezequielc @alex-deaconu @settinghead 
Some minor differences when staged on store
https://store-stage-4.risevision.com/account
https://store-stage-4.risevision.com/shopping-cart

They don't break functionality, just styling differences. We could open a card for that or add a fix to this PR. I think it's better to add the fix so that we follow the rule of not breaking any production code. I would have to open a new card for that and block my current work.

**Comment by alex-deaconu** [comment]
@ghislaineguerin sounds good. 

@olegrise FYI, you may be interested in this conversation as well. 

Thanks.

**Comment by settinghead** [comment]
@ghislaineguerin :+1:

**Comment by ezequielc** [comment]
@ghislaineguerin Agreed re. adding the fix now. Thanks!

**Comment by olegrise** [comment]
Totally agree. Thanks @alex-deaconu.

**Comment by ghislaineguerin** [comment]
@alex-deaconu @ezequielc @settinghead @olegrise 
I have updated common styles in order to fix the table issues on store. Please review attached links. Store will require minor changes to classes :
https://github.com/Rise-Vision/store/pull/1213

Store links with new styles:
https://store-stage-4.risevision.com/shopping-cart
https://store-stage-4.risevision.com/account
Apps link with new styles:
https://apps-stage-3.risevision.com/

**Comment by alex-deaconu** [comment]
@ghislaineguerin looks good to me 👍 . Thanks!

**Comment by olegrise** [comment]
@brianloosbrock FYI - see above.

**Pull request merged**
