### PR TITLE
CTA Tooltip class

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ezequielc 
Pull Request for the 'CTA Tooltip' UI. Would like to merge and tag a release along with 
https://github.com/Rise-Vision/common-style/pull/271
as soon as you're ready. Thanks!

**Comment by ezequielc** [comment]
@RV-Adrian 👍 Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc Thanks, tag release for you here: https://github.com/Rise-Vision/common-style/releases/tag/v1.3.81

**Comment by ezequielc** [comment]
@RV-Adrian Thank!

**Pull request merged**
