### PR TITLE
splash styles for designer referral page

### PR DESCRIPTION
**Pull request by mmeiers**

### CODE REVIEW

**Comment by donnapep** [comment]
@adriandd @ghislaineguerin @mmeiers I think we need to tag a new release since I'm not getting any of the changes in this PR when pulling down v1.3.

**Comment by donnapep** [comment]
@adriandd @ghislaineguerin @mmeiers I went ahead and tagged v1.3.1. Thx.

**Comment by RV-Adrian** [comment]
@donnapep Thanks Donna, was also having problems pulling in 1.3 :+1:

**Comment by mmeiers** [comment]
@RV-Adrian @donnapep @ghislaineguerin 
I suppose I don't know how to tag a new release. Can someone give me a brief explanation of what Donna just did?

**Comment by donnapep** [comment]
@mmeiers @adriandd I went to the Releases tab of the `common-style` repo. Then clicked the "Draft a new release" button. Then I just incremented the tag version and entered a description and a summary of the commits. Then clicked the "Publish release" button. Now you can pull that specific version down using Bower.

Ideally, the version numbers in `bower.json` and `package.json` should match the latest tagged release. Right now `bower.json` is at 0.4.0 and `package.json` is at 0.0.0.

**Comment by RV-Adrian** [comment]
@donnapep Thanks for the info! Agreed about the version numbers in bower/package.json. Would be nice to easily see the correct tag has been pulled in. Will have to make this part of our process.

**Comment by mmeiers** [comment]
@donnapep Ok thanks Donna! that helps

**Pull request merged**
