### PR TITLE
icon fixes

### PR DESCRIPTION
**Pull request by ghislaineguerin**

### CODE REVIEW

**Comment by ezequielc** [comment]
@ghislaineguerin Actually I found an issue with the Widgets modal. It seems to be caused because the Weather Forecast widget uses 2 lines for the name. Could you have a look? Thanks

screenshot from 2016-01-28 17 36 39

**Comment by ghislaineguerin** [comment]
@ezequielc I'll take a look.

**Comment by ghislaineguerin** [comment]
@ezequielc this is fixed.

**Comment by ezequielc** [comment]
@ghislaineguerin Thanks!

**Comment by ezequielc** [comment]
@RV-Adrian Staged at https://apps-stage-3.risevision.com/. Please review. Thanks

**Comment by ghislaineguerin** [comment]
@ezequielc looks good to me

**Comment by ezequielc** [comment]
Thanks @ghislaineguerin !

**Comment by RV-Adrian** [comment]
@ezequielc @ghislaineguerin :+1:

**Pull request merged**
