### PR TITLE
Feature/app launcher

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@RV-Adrian please take a look at this. We need to merge this branch in order to move forward with other cards. I'm trying to stage it but test is failing. 
@ezequielc could you take a look and stage the latest version of apps on production with these styles?

### CODE REVIEW

**Comment by ezequielc** [comment]
@ghislaineguerin Sure, I will do that. Cheers!

**Comment by RV-Adrian** [comment]
@ghislaineguerin @ezequielc will do. I'll check out the stage when ready, but changes look good so far.

**Comment by ghislaineguerin** [comment]
@RV-Adrian https://apps-stage-4.risevision.com/ staged now

**Comment by RV-Adrian** [comment]
@ghislaineguerin @ezequielc :+1: Thanks

**Comment by ghislaineguerin** [comment]
@RV-Adrian fixed common header issue, waiting for new stage link.

**Comment by ghislaineguerin** [comment]
@RV-Adrian updated https://apps-stage-4.risevision.com

**Pull request merged**
