### PR TITLE
Layout fix for new Store category

### PR DESCRIPTION
**Pull request by RV-Adrian**
@ghislaineguerin Small tweak to accomodate for new Category in Store menu.
@olegrise FYI

### CODE REVIEW

**Comment by olegrise** [comment]
@ghislaineguerin could you please review this PR? I'd like to merge this ASAP.

**Comment by brianloosbrock** [comment]
@olegrise @ghislaineguerin @RV-Adrian Whats the status of this? Thanks

**Comment by olegrise** [comment]
@RV-Adrian I don't think it makes sense to wait any longer. @ghislaineguerin is probably too busy with other things. The change looks good. Please merge this today. Thanks.

**Comment by RV-Adrian** [comment]
@olegrise Will do so now, thanks.

**Comment by olegrise** [comment]
Thanks @RV-Adrian. I assigned a tag to it `v1.3.6`.

**Comment by RV-Adrian** [comment]
@olegrise :+1:

**Comment by olegrise** [comment]
@RV-Adrian you forgot to include `rise.min.css`.

**Pull request merged**
