### PR TITLE
Sidebar changes

### PR DESCRIPTION
**Pull request by ezequielc**
@ghislaineguerin Please review. Staged at https://apps-stage-0.risevision.com
Thanks!

### CODE REVIEW

**Comment by ezequielc** [comment]
@ghislaineguerin I squashed the commits. Please review. Thanks!

**Comment by brianloosbrock** [comment]
@ezequielc Oleg is out today, can someone else review? Thanks

**Comment by ezequielc** [comment]
@brianloosbrock Sorry, I don't think I tagged Oleg. I mentioned @ghislaineguerin to review :) Cheers!

**Comment by ghislaineguerin** [comment]
@ezequielc looks good.

**Comment by brianloosbrock** [comment]
@ezequielc Sorry..I don't know what I was looking at!

**Pull request merged**
