### PR TITLE
Fix/storage container

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@RV-Adrian 
Changes to fix storage. Will post stage link soon.

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ghislaineguerin alright great! let me know the Stage number, thanks

**Comment by ghislaineguerin** [comment]
@RV-Adrian https://storage-stage-rva-test.risevision.com/

**Comment by RV-Adrian** [comment]
@ghislaineguerin Is it possible to test the bug from here since it's in-app?

**Comment by RV-Adrian** [comment]
@ghislaineguerin @fjvallarino Tested from http://rva-test.appspot.com/ and :+1: 
Merging now, then Tag release 1.3.11

**Pull request merged**
