### PR TITLE
Add CSS for Google drive picker icon

### PR DESCRIPTION
**Pull request by donnapep**
* Add CSS for Google drive picker icon.
* Add Gulp task for bumping version and updated `package.json` and `bower.json` to correct version.

### CODE REVIEW

**Comment by donnapep** [comment]
@RV-Adrian @ghislaineguerin Please review. This isn't staged anywhere yet but attached is a screenshot of the Google Drive picker component this will be used in.

Also, there is already CSS that this component was previously using [here](https://goo.gl/FIYnZj), but I wasn't sure if this was being used elsewhere so I left that as is.

Thx.
google-drive-picker

**Comment by RV-Adrian** [comment]
@donnapep Looks solid.
@ghislaineguerin Is that an outdated CSS reference?

**Comment by donnapep** [comment]
@RV-Adrian @ghislaineguerin Can this be merged? It's blocking my card. Thx.

**Comment by ghislaineguerin** [comment]
@donnapep looks ok. 👍

**Comment by donnapep** [comment]
@RV-Adrian @ghislaineguerin Thank you both.

**Pull request merged**
