### PR TITLE
scrolling list styles

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu PR for the scrolling list styles.

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@RV-Adrian Please take a look at this. It is a fix for broken scrollable lists and spacing on action sheets.

**Comment by ghislaineguerin** [comment]
@RV-Adrian http://ux-design.s3.amazonaws.com/scrolling-list/prototypes/scrolling-list/index.html
Updated link.

**Comment by RV-Adrian** [comment]
@ghislaineguerin Looks solid. Only thing I would hope for is maybe a sticky header on the table? So [Name - Status - Last Connection ] remains persistent if they scroll very far down.
Just my 2 cents, depends on scope and deadlines. :)

**Comment by RV-Adrian** [comment]
oh and :+1:

**Comment by ghislaineguerin** [comment]
@RV-Adrian Sticky header was part of the plan but was left for a separate card. Thanks for the review!

**Pull request merged**
