### PR TITLE
Feature/store filter

### PR DESCRIPTION
**Pull request by RV-Adrian**
@ghislaineguerin Cleaned up and re-opened. Thanks!

### CODE REVIEW

**Comment by RV-Adrian** [comment]
morning @ghislaineguerin ! 
@fjvallarino needs this merged before he can merge his own changes. Can we get approval to do so? Thanks

**Comment by ghislaineguerin** [comment]
@RV-Adrian it all looks pretty good to me. But 46 commits is a lot, can we squash this? @fjvallarino can you help Adrian with squashing this? and also let's get rid of gitignore file.

**Comment by RV-Adrian** [comment]
@ghislaineguerin Thanks, gitignore now removed (at last)
@fjvallarino Go for the squash when ready!
:+1:

**Comment by ghislaineguerin** [comment]
:+1: @fjvallarino @RV-Adrian

**Pull request merged**
