### PR TITLE
Remove duplicate vertical scrollbar

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @ghislaineguerin please review

### CODE REVIEW

**Comment by tejohnso** [comment]
Isn't this going to make the file listing unscrollable again?

**Comment by fjvallarino** [comment]
@tejohnso Check https://storage-stage-0.risevision.com. A new scrollbar appeared on the whole page, making this one a duplicate

**Comment by tejohnso** [comment]
:+1:

**Comment by ghislaineguerin** [comment]
@fjvallarino +1

**Pull request merged**
