### PR TITLE
blank state updates

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@RV-Adrian Here it is .See stage link for storage.

http://ux-design.s3.amazonaws.com/onboarding/prototypes/onboarding/storage.html

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@RV-Adrian seems like I'm missing some extra negative margin on top. I've only modified product-image
Do you think we should instead modify app-header for taking less space vertically on mobile res? Then the placement will be the same for all instances.

**Comment by RV-Adrian** [comment]
@ghislaineguerin That could work. Do you think that might have impact beyond these type of 'blank slate' screens though?

**Comment by ghislaineguerin** [comment]
@RV-Adrian I guess it is more of a concern of keeping each component independent and with their own set of responsive rules not dependent on the context? It will be easier to maintain. I could be wrong, what do you think?

**Comment by RV-Adrian** [comment]
@ghislaineguerin Makes sense, just thinking as an example:
If we change .app-header for this Blank Slate layout, would it have a negative impact on the .app-header at https://storage.risevision.com/ ? Or elsewhere?
Will defer to you on the scope of this. :) Just seems to be a commonly used thing.

**Pull request closed without merging**
