### PR TITLE
Fix for Navbar button sizes

### PR DESCRIPTION
**Pull request by RV-Adrian**
@ghislaineguerin Please review
@brianloosbrock FYI

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
:+1:

**Comment by RV-Adrian** [comment]
@ghislaineguerin Thx! Does this need to rebuild from Common Header then?

**Comment by RV-Adrian** [comment]
@ghislaineguerin This targets immediate children of navbar-right. Dropdowns look ok: https://goo.gl/5uZBQ8
Any place I should be testing specifically? Can stage it if you're curious.

Side note, I thought we agreed :+1:  meant 'all good, merge away'. Maybe we need something clearer?

**Comment by ghislaineguerin** [comment]
@RV-Adrian my bad, sorry, just wondering how it will affect the layout when in lower resolution.

**Comment by RV-Adrian** [comment]
@ghislaineguerin Gotcha, seems okay though: http://goo.gl/5LqO0w
Thoughts?

**Comment by ghislaineguerin** [comment]
@RV-Adrian perfect! sorry about that! I will only use the :+1: when it is good to merge.

**Comment by RV-Adrian** [comment]
@ghislaineguerin No worries! Thanks!
I'll go ahead and push this tag to Store, and we can play the other apps by ear. :)

**Pull request merged**
