### PR TITLE
Navigation updates

### PR DESCRIPTION
**Pull request by ezequielc**
@adriandd I squashed the commits and staged and https://apps-stage-4.risevision.com/
Please review. Thanks!
@alex-deaconu fyi

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ezequielc Thanks. I still see that odd gap to the right of 'Classic Editor'. Want me to look further?

**Comment by ezequielc** [comment]
@RV-Adrian I finally manage to build CH and the gap is still there. If you can, please have a look. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc That should fix it, please let me know if not. Thx!

**Comment by ezequielc** [comment]
@RV-Adrian Staged at https://apps-stage-4.risevision.com/
Please review. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc Looks solid :+1: 
Thanks

**Pull request merged**
