### PR TITLE
Website Styles

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@rodrigopavezi this is the PR for website styles
Please review
@RV-Adrian 
@mmeiers

### CODE REVIEW

**Comment by mmeiers** [comment]
:+1: Looks good. Do you typically squash commits like these?

**Comment by RV-Adrian** [comment]
Great! :+1:  
Request: Can we include online prototype links in PRs? Just for the convenience of seeing it in browser without having to dig a bit?

**Comment by rodrigopavezi** [comment]
:+1: LG

**Comment by ghislaineguerin** [comment]
@RV-Adrian yes, sorry about that. I forgot to include prototype:
https://website-stage-1.risevision.com/
@mmeiers I had 21 commits before, so I moved the changes to a new branch create from master for this reason, squashing was super complicated given how old the other branch was.

**Pull request merged**
