### PR TITLE
Added margin for inline Coupon removal button

### PR DESCRIPTION
**Pull request by RV-Adrian**
@ghislaineguerin @mmeiers Small update here, to make an inline 'Coupon Removal' button. Thanks!
@brianloosbrock FYI

S3 Prototype: http://ux-design.s3.amazonaws.com/store-coupons/prototypes/coupons/cart-v7.html
Task: https://trello.com/c/uQTSoh3e/509-tweak-coupon-remove-button-coming-out-of-share-and-learn

### CODE REVIEW

**Comment by mmeiers** [comment]
:+1: Are you using double space indent? Looks like its 4 spaces but not sure if thats just the github preview...

**Comment by RV-Adrian** [comment]
@mmeiers Nope, you got me there! Updated, thanks.

**Comment by RV-Adrian** [comment]
@ghislaineguerin @mmeiers Alexey is wrapping up Coupons now. I'll merge this tomorrow if all good, thanks.

**Comment by ghislaineguerin** [comment]
:+1:

**Comment by mmeiers** [comment]
:+1:

**Pull request merged**
