### PR TITLE
Feature/app styles

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu these were some cleanup and fixes that existed on feature/schedule branch. I have moved here only the ones we need for the apps.

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ghislaineguerin I don't see any build results in this PR, am I missing something? Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu sorry, I don't follow. It is only common-styles, no build I assume?

**Comment by alex-deaconu** [comment]
@ghislaineguerin basically, I don't see the updated `css` files in the `dist` folder. Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu sorry about that. I have added it now.

**Comment by alex-deaconu** [comment]
@ghislaineguerin nice. Looks good to me :+1: . Thanks.

**Pull request merged**
