### PR TITLE
Fix for RVA Modal Subscription Notice

### PR DESCRIPTION
**Pull request by RV-Adrian**
@fjvallarino I abandoned the modal height fix for now.  Would you be able to make a branch of 'storage-client', pull in these CS changes and stage it?  Let me know if there's any issues with that, thanks.

@brianloosbrock FYI

### CODE REVIEW

**Comment by brianloosbrock** [comment]
@fjvallarino Can you review asap and stage. We need to fix this today yet. Thanks

**Comment by fjvallarino** [comment]
@brianloosbrock This is already staged. As soon as @RV-Adrian tells me it's ready, I will approve.

**Comment by brianloosbrock** [comment]
@fjvallarino Thanks. Where can I review it at? What is the staged URL?

**Comment by brianloosbrock** [comment]
@RV-Adrian Francisco and I just reviewed the fix and it doesn't appear its fixed yet. It still looks the old way https://s3.amazonaws.com/uploads.hipchat.com/106443/1278097/a1F7vtbCmgskBfw/upload.png? @fjvallarino

**Comment by fjvallarino** [comment]
:+1:

**Comment by RV-Adrian** [comment]
@fjvallarino Thanks for the assistance! @brianloosbrock Check it out when ready

**Comment by brianloosbrock** [comment]
@RV-Adrian Thanks. I reviewed with @fjvallarino and the change looks good.

@ghislaineguerin Can you review and approve Adrian's change before we deploy. Thanks

**Comment by ghislaineguerin** [comment]
:+1: looks good.

**Comment by RV-Adrian** [comment]
@fjvallarino @brianloosbrock Merged, thanks

**Pull request merged**
