### PR TITLE
Feature/storage functions

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ghislaineguerin 
Please review changes for https://trello.com/c/P285m2Yo/1898-ux-prototype-rename-move-copy-buttons-and-modal-3 on https://apps-stage-3.risevision.com/
Thanks!

**Comment by ghislaineguerin** [comment]
👍

**Comment by alex-deaconu** [comment]
@RV-Adrian @ghislaineguerin as I'm working to integrate UX changes for Storage, I found this branch un-merged. I've rebased it to bring it up to date, wondering if you could take a quick look and review. Thanks!

**Comment by alex-deaconu** [comment]
Apps PR staged at https://apps-stage-1.risevision.com/storage

**Comment by RV-Adrian** [comment]
@alex-deaconu Looks solid 👍 Thanks!

**Pull request merged**
