### PR TITLE
New UX for font setting component

### PR DESCRIPTION
**Pull request by donnapep**
The font setting component is being refactored to use the toolbar icons from TinyMCE.

### CODE REVIEW

**Comment by donnapep** [comment]
@adriandd @ghislaineguerin @mmeiers Please review. Thx.

**Comment by RV-Adrian** [comment]
@donnapep Looks good, might this be staged anywhere?

**Comment by donnapep** [comment]
@adriandd Since this is just a component, we'd need to actually include it in one of our Widgets, and we can't really do that until the component is complete. Best I can do right now is a screenshot of my test page - http://screencast.com/t/rsxS7hf4b. Thx.

**Comment by RV-Adrian** [comment]
@donnapep That's perfect, looks solid to me. :+1: 
Thx!

**Comment by donnapep** [comment]
@adriandd Great, thx!

**Comment by mmeiers** [comment]
:+1: Looks good.

The github icon shouldn't be blue but I imagine that is just part of a test page...

**Comment by donnapep** [comment]
@mmeiers Yes, that's correct. It's just part of the test page. Thx.

**Pull request merged**
