### PR TITLE
Zoom Selector r update

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ghislaineguerin 
Some updates to '.zoom-selector' for the Zoom To Fit prototype. Thx!

**Comment by ghislaineguerin** [comment]
@RV-Adrian curious, what was the issue?

**Comment by ghislaineguerin** [comment]
@RV-Adrian otherwise it looks good 👍

**Comment by RV-Adrian** [comment]
@ghislaineguerin 
No issue, just expanding the Zoom feature.
Sorry I should have included the stage https://apps-stage-1.risevision.com

**Comment by ghislaineguerin** [comment]
@RV-Adrian 👍

**Pull request merged**
