### PR TITLE
storage selector fixes

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@fjvallarino there are some spacing issues on selector after last fixes
screen shot 2015-06-29 at 9 37 04 am
. These changes will fix it.

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@RV-Adrian Please review

**Comment by fjvallarino** [comment]
:+1:

**Comment by ghislaineguerin** [comment]
@mmeiers please review!
@RV-Adrian disregard message. Enjoy vacation :tropical_drink:

**Comment by mmeiers** [comment]
vh is specific to chrome, correct? Is that something we are good with using everywhere in ux? Just curious because i wanted to use it in my settings but refrained because I was unsure.

other than that...
:+1:

**Pull request merged**
