### PR TITLE
Amazon S3 hosting for Featured Product banners

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by olegrise** [comment]
@RV-Adrian see this article http://www.paulirish.com/2010/the-protocol-relative-url/. Do you think it makes sense to go with 
`background-image: url('//s3.amazonaws.com/StoreProducts/Featured+Products/featured_tiny_stocktrack.jpg');`
instead of 
`url('https://s3.amazonaws.com/StoreProducts/Featured+Products/featured_tiny_stocktrack.jpg');`

**Comment by RV-Adrian** [comment]
@olegrise True! I will update that. Looks like some of the Product images in Store could use that as well?

**Comment by RV-Adrian** [comment]
@olegrise Does the blurb at the top apply to us regarding SSL? 
(ie. 'this technique is now an anti-pattern')

**Comment by olegrise** [comment]
@RV-Adrian Ha-ha. I didn't even notice blurb. Well, if THEY say it's anti-pattern, then let's stick with HTTPS. Cheers!

**Comment by RV-Adrian** [comment]
@olegrise very good! :+1:

**Pull request merged**
