### PR TITLE
Offline Player update

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ghislaineguerin 
Please review https://trello.com/c/pvqFIe1K/2742-1-offline-epic-implementation-notes-ux

**Comment by ghislaineguerin** [comment]
@RV-Adrian is cell highlight the class to make text bold ?

**Comment by RV-Adrian** [comment]
@ghislaineguerin 
That's for 'Premium Add-Ons' : 
image


You can view this at https://apps-stage-2.risevision.com/displays/details/G679GYG8E5PZ
on the right side. Thx!

**Comment by ghislaineguerin** [comment]
@RV-Adrian looks good 👍

**Pull request merged**
