### PR TITLE
Feature/thumbnail view

### PR DESCRIPTION
**Pull request by RV-Adrian**
@alex-deaconu @ezequielc 
As we chatted about this morning, a branch to cover Thumbnail and get Playlist items just right (with arrows).

@alex-deaconu It looks like you will be using this with feature/playlist-layout ?
If so, going to have to revise this a bit.. just need to know what to cover. It looks like:
The as-prototyped Playlist Item, except with arrows instead of the grip:
(ie. Duration, tooltips. etc)
image

If that's right, I will adjust. Thx!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@RV-Adrian not sure what you mean. You want me to use this branch instead of feature/button-layout (https://github.com/Rise-Vision/common-style/tree/feature/button-layout)? Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu If you need the arrows (as above) then this is the one to work from.
Just need to know how it works with the rest of the Playlist items. As you can see (with the SVG icons and new buttons) it needs some additions.

**Comment by alex-deaconu** [comment]
With this branch it looks the same as your image: http://screencast.com/t/7sf5Zsq8P. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Got it, will make some adjustments.

**Comment by RV-Adrian** [comment]
@alex-deaconu Give it a try now and let me know of any issues you see. Thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian from what I can tell everything looks good, except for the Playlist Item padding seems slightly larger than it was before: http://screencast.com/t/Vwh1GSTk. Wondering if this is intentional? Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Definitely not intentional! Looks like an overlap in classes. Should be fixed now, with Playlist Items having no padding.

**Comment by alex-deaconu** [comment]
@RV-Adrian looks like it's fixed. Thanks for looking into this!

**Comment by ezequielc** [comment]
@RV-Adrian I think we are good to merge. Thanks!
@alex-deaconu fyi

**Comment by ezequielc** [comment]
@RV-Adrian Do you want to squash the commits? Thanks

**Comment by RV-Adrian** [comment]
@ezequielc Squashed! Thanks

**Comment by ezequielc** [comment]
@RV-Adrian 👍 Thanks

**Pull request merged**
