### PR TITLE
Gray Storage-Icon for Empty State

### PR DESCRIPTION
**Pull request by RV-Adrian**
@ghislaineguerin Style for gray icon in 'Empty State'. No changes to Common-SVG as of yet.
@fjvallarino FYI

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@RV-Adrian missing dist file only :+1:

**Comment by RV-Adrian** [comment]
@ghislaineguerin @fjvallarino Done!

**Comment by ghislaineguerin** [comment]
@fjvallarino can you help Adrian with the update needed for Minify bug? Not sure if this will bring back that bug.

**Comment by RV-Adrian** [comment]
@ghislaineguerin @fjvallarino Was wondering that too, i ran 'npm update' before the build?

**Comment by fjvallarino** [comment]
@RV-Adrian @ghislaineguerin No, you should only need to run "npm update" once. The only thing is that you should make sure this branch is rebased to master, so you grab the change to bower.json. You only need to run it once, not once for every branch, since npm packages are not pushed to git.

**Comment by ghislaineguerin** [comment]
:+1: then I guess it's ok. I will merge. Thanks @fjvallarino

**Pull request merged**
