### PR TITLE
Optimize Spacing and sidebar width variable

### PR DESCRIPTION
**Pull request by ghislaineguerin**

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@RV-Adrian please review

**Comment by RV-Adrian** [comment]
@ghislaineguerin 
I'd have to make changes in the Store to accommodate this:
http://goo.gl/Xc6YK1

Not sure why text is blue now?
What's the need behind the image height change?

**Comment by ghislaineguerin** [comment]
@RV-Adrian I have removed changes to the grid, I wasn't aware this was shared w/ store. PLease review

**Comment by RV-Adrian** [comment]
@ghislaineguerin ok thanks

**Pull request merged**
